apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-keda-network-policy
  namespace: openwhisk
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: openshift-keda
      podSelector: {}
    - podSelector: {}
  podSelector: {}
  policyTypes:
  - Ingress
status: {}
